### ISSUE TITLE
Who no Scriptfiles folder?

### ISSUE THREAD

**Issue by rajabilal555** [donsta3000/Small-County-RP#1]
Well I don't know why you did not upload a Scriptfiles folder, but I see a use of it in `modules/server/defines.pwn` at line `54`

CODE:
```sourcepawn
#define LOG_PATH "/Server Logs/%s.txt"
```

**Comment by donsta3000** [comment]
Scriptfiles folder? I'm pretty sure that doesn't save into the scriptfiles folder... doesn't that just save into a folder called 'Server Logs'?

I shall look into it nonetheless, when I have time.

**Comment by rajabilal555** [comment]
Well ofcourse it saves into the `/scriptfiles/Server Logs` :P
