### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by mrfancyfrancis** [donsta3000/Small-County-RP#7]
Whenever I add a killable FCNPC, they are invinsible.

It only happens on this particular build of the server.
When I compile it using other packages, the bug isn't present.

**Comment by donsta3000** [comment]
Not my issue. It is because you are spawning the NPC in the wrong virtual world.

**Comment by mrfancyfrancis** [comment]
Sorry I meant "Invincible".

I also checked the NPCs and they do spawn at the same Virtual World as the player (You could see them, you just cant damage them)
Anything I'm missing out?

**Comment by donsta3000** [comment]
My bad, I must have misread your message! Having said that, I'm not particularly interested in looking into this issue as you are using a third party script that was not intended for this gamemode. 
If I get some spare time I might look into it. It is most likely something to do with the fact that weapon damage is calculated on the server side, OnPlayerTakeDamage.
